// frontend/src/components/layout/Header.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter, usePathname } from "next/navigation";
import { CloudUpload, User as UserIcon, LogOut, Menu, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { authService, User } from "@/services/authService";
import { toastService } from "@/services/toastService";

export function Header() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [displayName, setDisplayName] = useState("User");
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);
  const router = useRouter();
  const pathname = usePathname();

  // Enhanced display name logic matching Angular
  const updateUserDisplay = (user: User) => {
    let fullName = '';
    
    // Priority order: name > email username
    if (user.name) {
      fullName = user.name;
    } else if (user.email) {
      fullName = user.email.split('@')[0];
    }
    
    // Truncate if too long (max 8 characters for UI)
    const name = fullName.trim();
    setDisplayName(name.length > 8 ? `${name.substring(0, 8)}...` : name || 'User');
  };
  
  const checkAuthState = async () => {
    const authenticated = authService.isAuthenticated();
    setIsLoggedIn(authenticated);
    
    if (authenticated) {
      const user = authService.getCurrentUser();
      setCurrentUser(user);
      
      if (!user) {
        // If no user data, try to load it
        try {
          const userData = await authService.loadUserProfile();
          setCurrentUser(userData);
          updateUserDisplay(userData);
        } catch (error) {
          // If loading fails, logout
          authService.logout();
          setIsLoggedIn(false);
          setCurrentUser(null);
          setDisplayName('User');
        }
      } else {
        updateUserDisplay(user);
      }
    } else {
      setCurrentUser(null);
      setDisplayName('User');
    }
  };
  
  useEffect(() => {
    checkAuthState();

    window.addEventListener("storage", checkAuthState);
    window.addEventListener("focus", checkAuthState);
    window.addEventListener("authStateChanged", checkAuthState);

    const handleScroll = () => {
      setIsScrolled(window.scrollY > 10);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("storage", checkAuthState);
      window.removeEventListener("focus", checkAuthState);
      window.removeEventListener("authStateChanged", checkAuthState);
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  // Close mobile menu on route change
  useEffect(() => {
    if (isMobileMenuOpen) {
      setIsMobileMenuOpen(false);
    }
  }, [pathname]);

  const handleLogout = () => {
    try {
      authService.logout();
      setIsLoggedIn(false);
      setCurrentUser(null);
      setDisplayName('User');
      setIsMobileMenuOpen(false);
      
      toastService.success('Logged out successfully', 2500);
      router.push('/');
    } catch (error) {
      toastService.error('Logout failed. Please try again.', 2500);
    }
  };

  const closeMobileMenu = () => setIsMobileMenuOpen(false);

  const AuthButtons = ({ isMobile = false }: { isMobile?: boolean }) => (
    <div
      className={cn(
        "flex items-center",
        isMobile
          ? "flex-col w-full space-y-3"
          : "space-x-3"
      )}
    >
      {isLoggedIn ? (
        <>
          <Link
            href="/profile"
            onClick={closeMobileMenu}
            className={cn(
              "flex items-center justify-center space-x-2 bg-bolt-blue text-white rounded-xl hover:bg-bolt-mid-blue shadow-sm transition-all duration-300",
              isMobile ? "w-full h-[56px]" : "w-[140px] h-[44px]"
            )}
          >
            <div className="flex items-center justify-center rounded-full bg-white/20 w-7 h-7">
              <UserIcon className="w-4 h-4 text-white" />
            </div>
            <span className="text-sm font-semibold truncate">Profile</span>
          </Link>
          <button
            onClick={handleLogout}
            className={cn(
              "flex items-center justify-center space-x-2 bg-red-600 text-white rounded-xl hover:bg-red-700 shadow-sm transition-all duration-300",
              isMobile ? "w-full h-[56px]" : "w-[140px] h-[44px]"
            )}
          >
            <LogOut className="w-4 h-4 text-white" />
            <span className="text-sm font-semibold">Logout</span>
          </button>
        </>
      ) : (
        <>
          <Link
            href="/login"
            onClick={closeMobileMenu}
            className={cn(
              "flex items-center justify-center bg-gray-100 text-gray-700 hover:bg-gray-200 font-semibold rounded-xl transition-all duration-300",
              isMobile ? "w-full h-[56px]" : "w-[120px] h-[44px]"
            )}
          >
            Login
          </Link>
          <Link
            href="/register"
            onClick={closeMobileMenu}
            className={cn(
              "flex items-center justify-center bg-gradient-to-r from-bolt-blue to-bolt-mid-blue text-white font-bold rounded-xl transition-all duration-300 hover:shadow-lg",
               isMobile ? "w-full h-[56px] text-lg" : "h-[44px] px-6 text-sm"
            )}
          >
            Start Free
          </Link>
        </>
      )}
    </div>
  );

  return (
    <>
      <header
        className={cn(
          "sticky top-0 z-50 transition-all duration-300 backdrop-blur-xl bg-white border-b border-gray-300",
          isScrolled
            ? "shadow-lg border-b border-slate-200/80"
            : "border-b"
        )}
      >
        <div className="container px-4 mx-auto">
          <div className="flex items-center justify-between h-20">
            {/* Logo */}
            <Link href="/" className="flex items-center space-x-3">
              <div className="flex items-center justify-center w-10 h-10 shadow-lg bg-bolt-blue rounded-xl">
                <CloudUpload className="w-5 h-5 text-white" />
              </div>
              <span className="text-2xl font-bold text-transparent bg-gradient-to-r from-bolt-black to-bolt-medium-black bg-clip-text">
                Mfcnextgen
              </span>
            </Link>

            {/* Desktop Navigation */}
            <nav className="items-center hidden space-x-8 lg:flex">
              <Link
                href="/how-it-works"
                className="relative text-sm font-medium transition-colors duration-300 group text-bolt-medium-black hover:text-bolt-blue"
              >
                How it Works
                <span className="absolute bottom-[-4px] left-0 h-0.5 w-0 bg-gradient-to-r from-bolt-blue to-bolt-purple transition-all duration-300 group-hover:w-full"></span>
              </Link>
            </nav>

            {/* Desktop Auth Buttons */}
            <div className="hidden lg:flex">
              <AuthButtons />
            </div>

            {/* Mobile Menu Toggle */}
            <div className="lg:hidden">
              <button
                onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                className="p-2 bg-white border border-gray-200 rounded-lg hover:bg-gray-100"
                aria-label="Toggle menu"
              >
                {isMobileMenuOpen ? (
                  <X className="w-6 h-6 text-gray-700" />
                ) : (
                  <Menu className="w-6 h-6 text-gray-700" />
                )}
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Mobile Menu Overlay */}
      {isMobileMenuOpen && (
        <div className="fixed inset-0 z-40 pt-20 overflow-y-auto bg-white lg:hidden animate-fade-in-down">
          <div className="container flex flex-col h-full px-4 mx-auto">
            <nav className="flex-grow">
              <Link
                href="/how-it-works"
                onClick={closeMobileMenu}
                className="flex items-center justify-between w-full px-4 py-4 text-lg font-medium text-gray-700 transition-colors rounded-lg hover:bg-gray-50 hover:text-bolt-blue"
              >
                <span>How it Works</span>
                <ChevronRight className="w-5 h-5 text-gray-400" />
              </Link>
            </nav>
            <div className="pb-8 mt-auto">
              <AuthButtons isMobile />
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// Simple ChevronRight icon for mobile menu
const ChevronRight = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <path d="m9 18 6-6-6-6" />
  </svg>
);

// frontend/src/app/shared/component/header/header.component.ts
import { Component, OnInit, HostListener, OnDestroy } from '@angular/core';
import { AuthService } from '../../../services/auth.service';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit, OnDestroy {
  isLoggedIn = false;
  currentUser: any = null;
  isSticky = false;
  displayName = 'User';
  isScrollAnimation = false;
  lastScrollY = 0;
  isMobileMenuOpen = false;
  private authSubscription: Subscription | null = null;

  constructor(
    private authService: AuthService, 
    private router: Router
  ) {}

  ngOnInit(): void {
    // Subscribe to authentication state changes
    this.authSubscription = this.authService.isAuthenticated$.subscribe(isAuthenticated => {
      this.isLoggedIn = isAuthenticated;
      this.updateUserDisplay();
    });

    // Subscribe to current user changes
    this.authService.currentUser$.subscribe(user => {
      this.currentUser = user;
      this.updateUserDisplay();
    });

    // Check initial authentication state
    this.checkAuthState();
    
    // Listen to router events to update auth state
    this.router.events.subscribe(() => {
      this.checkAuthState();
    });
    
    // Ensure scroll animation is disabled on mobile devices on initialization
    this.initializeScrollAnimation();
  }

  ngOnDestroy(): void {
    if (this.authSubscription) {
      this.authSubscription.unsubscribe();
    }
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    const scrollY = window.scrollY;
    
    // Add sticky class when scrolled down
    this.isSticky = scrollY > 50;
    
    // Only trigger scroll animation on desktop (screens wider than 1024px)
    if (window.innerWidth > 1024) {
      // Check if user scrolled down from near the top
      if (scrollY > 10 && this.lastScrollY <= 10) {
        // User scrolled down from the top - trigger animation
        this.isScrollAnimation = true;
        
        // Remove animation class after animation completes
        setTimeout(() => {
          this.isScrollAnimation = false;
        }, 600); // Match animation duration
      }
    } else {
      // On mobile devices, ensure scroll animation is disabled
      this.isScrollAnimation = false;
    }
    
    // Update last scroll position
    this.lastScrollY = scrollY;
  }

  @HostListener('window:resize', [])
  onWindowResize() {
    // Close mobile menu on window resize to desktop
    if (window.innerWidth >= 1024) {
      this.isMobileMenuOpen = false;
    }
  }

  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  closeMobileMenu(): void {
    this.isMobileMenuOpen = false;
  }

  private updateUserDisplay(): void {
    if (this.isLoggedIn && this.currentUser) {
      this.displayName = this.getDisplayName(this.currentUser);
    } else {
      this.displayName = 'User';
    }
  }

  private initializeScrollAnimation(): void {
    // Disable scroll animation on mobile devices
    if (window.innerWidth <= 1024) {
      this.isScrollAnimation = false;
    }
  }

  private checkAuthState(): void {
    // Use the auth service to check authentication
    this.isLoggedIn = this.authService.isAuthenticated();
    
    if (this.isLoggedIn) {
      // Get current user from auth service
      this.currentUser = this.authService.getCurrentUser();
      if (!this.currentUser) {
        // If no user data, try to load it
        this.authService.loadUserProfile().subscribe({
          next: (user) => {
            this.currentUser = user;
            this.updateUserDisplay();
          },
          error: (error) => {
            console.error('Failed to load user data:', error);
            // If loading fails, logout
            this.authService.logout();
          }
        });
      } else {
        this.updateUserDisplay();
      }
    } else {
      this.currentUser = null;
      this.displayName = 'User';
    }
  }

  private getDisplayName(user: any): string {
    let fullName = '';
    
    // Try to get username first, then first name, then email, then fallback
    if (user?.username) {
      fullName = user.username;
    } else if (user?.first_name) {
      fullName = user.first_name;
    } else if (user?.email) {
      // Extract username from email (part before @)
      const emailParts = user.email.split('@');
      fullName = emailParts[0];
    } else {
      return 'User';
    }
    
    // Return shortened version (first 8 characters max)
    return fullName.length > 8 ? fullName.substring(0, 8) + '...' : fullName;
  }

  private isTokenExpired(token: string): boolean {
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      const currentTime = Math.floor(Date.now() / 1000);
      return payload.exp < currentTime;
    } catch (error) {
      return true; // If we can't parse the token, consider it expired
    }
  }

  logout(): void {
    console.log('[HEADER] Logout initiated by user');
    this.authService.logout();
    
    // Clear local state immediately
    this.isLoggedIn = false;
    this.currentUser = null;
    this.displayName = 'User';
    this.isMobileMenuOpen = false;
    
    // Navigate to home page after logout
    this.router.navigate(['/']);
  }
}

<!-- Enhanced Header with Modern Design -->
<header class="border-b bg-white backdrop-blur-md shadow-lg fixed top-0 left-0 right-0 z-50 premium-header transition-all duration-300" 
        [class.header-sticky]="isSticky"
        [class.header-scroll-animation]="isScrollAnimation">
  <!-- Enhanced Geometric Accent -->
  <div class="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 opacity-70"></div>
  
  <div class="container mx-auto px-4 py-3">
    <div class="flex items-center justify-between">
      <!-- Enhanced Logo Section -->
      <div class="flex items-center space-x-3">
        <div class="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
          <!-- Enhanced Cloud Upload icon -->
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
          </svg>
        </div>
        <a routerLink="/" class="text-2xl font-bold bg-gradient-to-r from-gray-800 to-gray-600 bg-clip-text text-transparent hover:from-blue-600 hover:to-purple-600 transition-all duration-300">
          Mfcnextgen
        </a>
      </div>

      <!-- Enhanced Navigation - Desktop -->
      <nav class="hidden lg:flex items-center space-x-8 mr-8">
        <a href="#how-it-works" class="nav-link text-gray-700 hover:text-blue-600 transition-all duration-300 font-medium text-sm relative group">
          How it Works
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-300 group-hover:w-full"></span>
        </a>
        <a href="#pricing" class="nav-link text-gray-700 hover:text-blue-600 transition-all duration-300 font-medium text-sm relative group">
          Pricing
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-300 group-hover:w-full"></span>
        </a>
      </nav>

      <!-- Enhanced Navigation Section - Desktop Only -->
      <div class="hidden lg:flex items-center space-x-3">
        <!-- For authenticated users: Enhanced Profile Section -->
        <div *ngIf="isLoggedIn" class="flex items-center space-x-3">
          <!-- Enhanced Profile Button -->
          <a routerLink="/profile" class="flex items-center space-x-2 bg-blue-700 text-white px-4 py-2.5 rounded-xl hover:bg-blue-800  shadow-sm w-[140px] h-[44px] justify-center">
            <div class="w-7 h-7 bg-white bg-opacity-20 rounded-full flex items-center justify-center shadow-sm">
              <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
              </svg>
            </div>
            <span class="font-semibold text-sm truncate text-white">{{ displayName }}</span>
          </a>
          
          <!-- Enhanced Logout Button -->
          <button (click)="logout()" class="flex items-center space-x-2 bg-red-600 text-white px-4 py-2.5 rounded-xl hover:bg-red-700  shadow-sm w-[140px] h-[44px] justify-center">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
            </svg>
            <span class="font-semibold text-sm text-white">Logout</span>
          </button>
        </div>
        
        <!-- For anonymous users: Enhanced Login/Register -->
        <div *ngIf="!isLoggedIn" class="flex items-center space-x-3">
          <a routerLink="/login" class="bg-gray-100 text-gray-700 hover:bg-gray-200 font-semibold transition-all duration-300 px-6 py-2.5 rounded-xl w-[120px] h-[44px] flex items-center justify-center">
            Login
          </a>
          
          <!-- Enhanced Start Free Button -->
          <a routerLink="/register" class="premium-button bg-gradient-to-r from-blue-600 to-blue-700 text-white px-6 py-2.5 rounded-xl font-bold hover:from-blue-700 hover:to-blue-800 flex items-center justify-center">
            Start Free
          </a>
        </div>
      </div>

      <!-- Mobile Menu Button - Simple Design -->
      <button class="lg:hidden p-2 rounded-lg hover:bg-gray-100  border border-gray-200" (click)="toggleMobileMenu()">
        <svg class="w-6 h-6 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>
    </div>
  </div>
  
  <!-- Enhanced Gradient Line -->
  <div class="h-px bg-gradient-to-r from-transparent via-blue-400 to-transparent opacity-60"></div>
</header>

<!-- Full Screen Mobile Menu Overlay -->
<div *ngIf="isMobileMenuOpen" class="lg:hidden fixed inset-0 bg-white z-40 pt-20">
  <div class="container mx-auto px-4 h-full flex flex-col">
    <div class="flex flex-col space-y-6 flex-1">
      <!-- Mobile Navigation -->
      <div class="space-y-3">
        <a href="#how-it-works" (click)="closeMobileMenu()" class="flex items-center justify-between text-gray-700 hover:text-blue-600 font-medium py-3 px-4 rounded-lg hover:bg-gray-50 transition-all duration-300 text-lg">
          <span>How it Works</span>
          <svg class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
          </svg>
        </a>
        <a href="#pricing" (click)="closeMobileMenu()" class="flex items-center justify-between text-gray-700 hover:text-blue-600 font-medium py-3 px-4 rounded-lg hover:bg-gray-50 transition-all duration-300 text-lg">
          <span>Pricing</span>
          <svg class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
          </svg>
        </a>
      </div>
      
      <!-- Mobile Auth Buttons - Stacked Vertically -->
      <div *ngIf="!isLoggedIn" class="flex flex-col space-y-3 mt-auto pb-8">
        <a routerLink="/login" (click)="closeMobileMenu()" class="bg-gray-100 text-gray-700 hover:bg-gray-200 font-semibold py-2 px-6 rounded-lg transition-all duration-300 text-center text-sm w-full h-[56px] flex items-center justify-center">
          Login
        </a>
        <a routerLink="/register" (click)="closeMobileMenu()" class="premium-button bg-gradient-to-r from-blue-600 to-blue-700 text-white py-2 px-6 rounded-lg font-bold transition-all duration-300 text-center text-lg w-full h-[56px] flex items-center justify-center">
          Start Free
        </a>
      </div>
      
      <!-- Mobile Profile Section - Stacked Vertically -->
      <div *ngIf="isLoggedIn" class="flex flex-col space-y-3 mt-auto pb-8">
        <a routerLink="/profile" (click)="closeMobileMenu()" class="flex items-center justify-center space-x-3 bg-blue-700 text-white px-6 py-2 rounded-lg text-sm w-full h-[56px]">
          <div class="w-6 h-6 bg-white bg-opacity-20 rounded-full flex items-center justify-center">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
            </svg>
          </div>
          <span class="font-semibold truncate text-white">{{ displayName }}</span>
        </a>
        <button (click)="logout()" class="flex items-center justify-center space-x-3 bg-red-600 text-white px-6 py-2 rounded-lg text-sm w-full h-[56px]">
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
          </svg>
          <span class="font-semibold text-white">Logout</span>
        </button>
      </div>
    </div>
  </div>
</div>
