// frontend/src/app/admin-panel/create-admin/create-admin.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AdminAuthService } from '../../services/admin-auth.service';
import { AdminUserCreate, UserRole } from '../../models/admin.model';

@Component({
  selector: 'app-create-admin',
  templateUrl: './create-admin.component.html',
  styleUrls: ['./create-admin.component.css']
})
export class CreateAdminComponent implements OnInit {
  createAdminForm: FormGroup;
  loading = false;
  error = '';
  success = '';
  userRoles = UserRole;
  isSuperAdmin = false;
  showPassword = false;
  showConfirmPassword = false;
  passwordStrength = '';

  constructor(
    private formBuilder: FormBuilder,
    private adminAuthService: AdminAuthService,
    private router: Router
  ) {
    this.createAdminForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
      confirmPassword: ['', [Validators.required]],
      role: [UserRole.ADMIN, [Validators.required]]
    }, {
      validators: this.passwordMatchValidator
    });

    // Add password strength monitoring
    this.createAdminForm.get('password')?.valueChanges.subscribe(password => {
      this.passwordStrength = this.calculatePasswordStrength(password);
    });
  }

  ngOnInit(): void {
    // Check if current user is superadmin
    this.isSuperAdmin = this.adminAuthService.isSuperAdmin();
    
    if (!this.isSuperAdmin) {
      this.error = 'Only superadmin can create new admin users';
      return;
    }

    // Check admin authentication
    if (!this.adminAuthService.isAdminAuthenticated()) {
      this.router.navigate(['/admin-login']);
    }
  }

  get f() {
    return this.createAdminForm.controls;
  }

  togglePasswordVisibility(field: 'password' | 'confirmPassword'): void {
    if (field === 'password') {
      this.showPassword = !this.showPassword;
    } else {
      this.showConfirmPassword = !this.showConfirmPassword;
    }
  }

  calculatePasswordStrength(password: string): string {
    if (!password) return '';
    
    let strength = 0;
    if (password.length >= 8) strength++;
    if (/[a-z]/.test(password)) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[^A-Za-z0-9]/.test(password)) strength++;
    
    if (strength <= 2) return 'weak';
    if (strength <= 3) return 'medium';
    return 'strong';
  }

  getPasswordStrengthColor(): string {
    switch (this.passwordStrength) {
      case 'weak': return '#ef4444';
      case 'medium': return '#f59e0b';
      case 'strong': return '#10b981';
      default: return '#6b7280';
    }
  }

  getPasswordStrengthText(): string {
    switch (this.passwordStrength) {
      case 'weak': return 'Weak password';
      case 'medium': return 'Medium strength';
      case 'strong': return 'Strong password';
      default: return '';
    }
  }

  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password');
    const confirmPassword = form.get('confirmPassword');
    
    if (password && confirmPassword && password.value !== confirmPassword.value) {
      return { passwordMismatch: true };
    }
    return null;
  }

  onSubmit(): void {
    if (this.createAdminForm.invalid || !this.isSuperAdmin) {
      return;
    }

    this.loading = true;
    this.error = '';
    this.success = '';

    const adminData: AdminUserCreate = {
      email: this.f['email'].value,
      password: this.f['password'].value,
      role: this.f['role'].value
    };

    this.adminAuthService.createAdminUser(adminData).subscribe({
      next: (response) => {
        this.loading = false;
        this.success = `Admin user ${response.data.email} created successfully with role ${response.data.role}`;
        this.createAdminForm.reset();
        this.createAdminForm.patchValue({ role: UserRole.ADMIN });
        this.passwordStrength = '';
      },
      error: (error) => {
        this.loading = false;
        this.error = error.message || 'Failed to create admin user';
      }
    });
  }

  // goBack method removed - now part of admin panel layout

  getRoleDisplayName(role: UserRole): string {
    switch (role) {
      case UserRole.ADMIN:
        return 'Admin';
      case UserRole.SUPERADMIN:
        return 'Super Admin';
      default:
        return 'Unknown';
    }
  }
}
<div class="create-admin-container">
  <div class="create-admin-content">
    <div class="px-6 py-4 border-b border-gray-200">
      <div class="flex items-center justify-between">
        <h2 class="text-2xl font-bold text-gray-900">Create Admin User</h2>

      </div>
      <p class="mt-1 text-sm text-gray-600">
        Create new admin user accounts (Superadmin only)
      </p>
    </div>

    <div class="px-6 py-6">
      <!-- Super Admin Check -->
      <div *ngIf="!isSuperAdmin" class="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path>
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">Access Denied</h3>
            <div class="mt-2 text-sm text-red-700">
              <p>Only superadmin users can create new admin accounts.</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Create Admin Form -->
      <form *ngIf="isSuperAdmin" [formGroup]="createAdminForm" (ngSubmit)="onSubmit()" class="space-y-6">
        <!-- Email Field -->
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">
            Email Address
          </label>
          <input
            id="email"
            type="email"
            formControlName="email"
            class="mt-1 block w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            [class.border-red-300]="f['email'].invalid && f['email'].touched"
            [class.border-gray-300]="!(f['email'].invalid && f['email'].touched)"
            placeholder="admin@example.com"
          />
          <div *ngIf="f['email'].invalid && f['email'].touched" class="mt-1 text-sm text-red-600">
            <div *ngIf="f['email'].errors?.['required']">Email is required</div>
            <div *ngIf="f['email'].errors?.['email']">Please enter a valid email</div>
          </div>
        </div>

        <!-- Password Field -->
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">
            Password
          </label>
          <div class="relative">
            <input
              id="password"
              [type]="showPassword ? 'text' : 'password'"
              formControlName="password"
              class="mt-1 block w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 pr-12"
              [class.border-red-300]="f['password'].invalid && f['password'].touched"
              [class.border-gray-300]="!(f['password'].invalid && f['password'].touched)"
              placeholder="Minimum 8 characters"
            />
            <button
              type="button"
              (click)="togglePasswordVisibility('password')"
              class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
            >
              <i [class]="showPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
            </button>
          </div>
          
          <!-- Password Strength Indicator -->
          <div *ngIf="f['password'].value && passwordStrength" class="mt-2">
            <div class="flex items-center space-x-2">
              <div class="flex-1 bg-gray-200 rounded-full h-2">
                <div 
                  class="h-2 rounded-full transition-all duration-300"
                  [style.width.%]="passwordStrength === 'weak' ? 33 : passwordStrength === 'medium' ? 66 : 100"
                  [style.background-color]="getPasswordStrengthColor()"
                ></div>
              </div>
              <span 
                class="text-xs font-medium"
                [style.color]="getPasswordStrengthColor()"
              >
                {{ getPasswordStrengthText() }}
              </span>
            </div>
          </div>
          
          <div *ngIf="f['password'].invalid && f['password'].touched" class="mt-1 text-sm text-red-600">
            <div *ngIf="f['password'].errors?.['required']">Password is required</div>
            <div *ngIf="f['password'].errors?.['minlength']">Password must be at least 8 characters</div>
          </div>
        </div>

        <!-- Confirm Password Field -->
        <div>
          <label for="confirmPassword" class="block text-sm font-medium text-gray-700">
            Confirm Password
          </label>
          <div class="relative">
            <input
              id="confirmPassword"
              [type]="showConfirmPassword ? 'text' : 'password'"
              formControlName="confirmPassword"
              class="mt-1 block w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 pr-12"
              [class.border-red-300]="(f['confirmPassword'].invalid || createAdminForm.errors?.['passwordMismatch']) && f['confirmPassword'].touched"
              [class.border-gray-300]="!((f['confirmPassword'].invalid || createAdminForm.errors?.['passwordMismatch']) && f['confirmPassword'].touched)"
              placeholder="Confirm password"
            />
            <button
              type="button"
              (click)="togglePasswordVisibility('confirmPassword')"
              class="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
            >
              <i [class]="showConfirmPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
            </button>
          </div>
          
          <div *ngIf="(f['confirmPassword'].invalid || createAdminForm.errors?.['passwordMismatch']) && f['confirmPassword'].touched" class="mt-1 text-sm text-red-600">
            <div *ngIf="f['confirmPassword'].errors?.['required']">Please confirm password</div>
            <div *ngIf="createAdminForm.errors?.['passwordMismatch']">Passwords do not match</div>
          </div>
        </div>

        <!-- Role Field -->
        <div>
          <label for="role" class="block text-sm font-medium text-gray-700">
            Admin Role
          </label>
          <select
            id="role"
            formControlName="role"
            class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
          >
            <option [value]="userRoles.ADMIN">{{ getRoleDisplayName(userRoles.ADMIN) }}</option>
            <option [value]="userRoles.SUPERADMIN">{{ getRoleDisplayName(userRoles.SUPERADMIN) }}</option>
          </select>
        </div>

        <!-- Success Message -->
        <div *ngIf="success" class="bg-green-50 border border-green-200 rounded-md p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
              </svg>
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium text-green-800">{{ success }}</p>
            </div>
          </div>
        </div>

        <!-- Error Message -->
        <div *ngIf="error" class="bg-red-50 border border-red-200 rounded-md p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path>
              </svg>
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium text-red-800">{{ error }}</p>
            </div>
          </div>
        </div>

        <!-- Submit Button -->
        <div class="flex justify-end space-x-3">

          <button
            type="submit"
            [disabled]="loading || createAdminForm.invalid"
            class="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            [class.bg-indigo-600]="!loading && createAdminForm.valid"
            [class.hover:bg-indigo-700]="!loading && createAdminForm.valid"
            [class.bg-gray-400]="loading || createAdminForm.invalid"
            [class.cursor-not-allowed]="loading || createAdminForm.invalid"
          >
            <span *ngIf="loading" class="inline-flex items-center">
              <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
              Creating...
            </span>
            <span *ngIf="!loading">Create Admin User</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

// frontend/src/app/admin-panel/create-admin/page.tsx
"use client";

import { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useRouter } from "next/navigation";
import { UserPlus, Mail, Lock, Eye, EyeOff, Loader2, AlertTriangle, CheckCircle2, ArrowLeft } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAdminAuth } from "@/hooks/useAdminAuth";
import { adminAuthService, AdminUserCreate } from "@/services/adminAuthService";
import { UserRole } from "@/types/admin";
import { toastService } from "@/services/toastService";

const formSchema = z.object({
  email: z.string().min(1, "Email is required").email("Please enter a valid email"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  confirmPassword: z.string().min(1, "Please confirm password"),
  role: z.nativeEnum(UserRole),
}).refine(data => data.password === data.confirmPassword, {
  message: "Passwords do not match",
  path: ["confirmPassword"],
});

type FormValues = z.infer<typeof formSchema>;

const PasswordStrengthIndicator = ({ password }: { password?: string }) => {
  const [strength, setStrength] = useState({ 
    score: 0, 
    width: "0%", 
    color: "bg-slate-200", 
    text: "", 
    label: "weak" as "weak" | "medium" | "strong" 
  });

  useEffect(() => {
    if (!password) {
      setStrength({ 
        score: 0, 
        width: "0%", 
        color: "bg-slate-200", 
        text: "", 
        label: "weak" 
      });
      return;
    }

    // Calculate password strength exactly like Angular
    let score = 0;
    if (password.length >= 8) score++;
    if (/[a-z]/.test(password)) score++;
    if (/[A-Z]/.test(password)) score++;
    if (/[0-9]/.test(password)) score++;
    if (/[^A-Za-z0-9]/.test(password)) score++;

    // Determine strength level and styling exactly like Angular
    let width = "0%";
    let color = "bg-[#ef4444]"; // red
    let text = "";
    let label: "weak" | "medium" | "strong" = "weak";

    if (score <= 2) {
      width = "33%";
      color = "bg-[#ef4444]"; // red
      text = "Weak password";
      label = "weak";
    } else if (score === 3) {
      width = "66%";
      color = "bg-[#f59e0b]"; // orange
      text = "Medium strength";
      label = "medium";
    } else if (score >= 4) {
      width = "100%";
      color = "bg-[#10b981]"; // green
      text = "Strong password";
      label = "strong";
    }
    
    setStrength({ score, width, color, text, label });
  }, [password]);

  if (!password) return null;

  return (
    <div className="mt-2">
      <div className="w-full h-2 rounded-full bg-slate-200 dark:bg-slate-700">
        <div 
          className={cn("h-2 rounded-full transition-all duration-300", strength.color)} 
          style={{ width: strength.width }} 
        />
      </div>
      {strength.text && (
        <p className={cn(
          "mt-1 text-xs font-medium",
          strength.label === "weak" && "text-red-600 dark:text-red-400",
          strength.label === "medium" && "text-orange-600 dark:text-orange-400", 
          strength.label === "strong" && "text-green-600 dark:text-green-400"
        )}>
          {strength.text}
        </p>
      )}
    </div>
  );
};

export default function CreateAdminPage() {
  const router = useRouter();
  const { isSuperAdmin, isAuthenticated } = useAdminAuth();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isInitializing, setIsInitializing] = useState(true);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: { email: "", password: "", confirmPassword: "", role: UserRole.ADMIN },
    mode: 'onChange', // Enable real-time validation
  });

  const passwordValue = form.watch("password");

  // Helper function to get role display name (matching Angular)
  const getRoleDisplayName = (role: UserRole): string => {
    switch (role) {
      case UserRole.ADMIN:
        return 'Admin';
      case UserRole.SUPERADMIN:
        return 'Super Admin';
      default:
        return 'Unknown';
    }
  };

  // Check authentication on mount - let the layout handle redirects
  useEffect(() => {
    if (!isAuthenticated) {
      // Don't redirect here - let the admin panel layout handle it
      setIsInitializing(false);
      return;
    }
    setIsInitializing(false);
  }, [isAuthenticated]);

  const onSubmit = async (data: FormValues) => {
    // 1. Validate superadmin access
    if (!isSuperAdmin()) {
      const errorMsg = "Only superadmin can create new admin users";
      setError(errorMsg);
      toastService.error(errorMsg);
      return;
    }

    // 2. Set loading state
    setLoading(true);
    
    // 3. Clear previous messages
    setError("");
    setSuccess("");

    const adminData: AdminUserCreate = {
      email: data.email,
      password: data.password,
      role: data.role,
    };

    try {
      // 4. Call adminAuthService.createAdminUser
      const response = await adminAuthService.createAdminUser(adminData);
      
      // 5. Handle success: show message, toast, reset form
      const successMsg = `Admin user ${response.data.email} created successfully with role ${response.data.role}`;
      setSuccess(successMsg);
      toastService.success("Admin user created successfully!");
      
      // Reset form exactly like Angular - reset then set role to ADMIN default
      form.reset();
      form.setValue('role', UserRole.ADMIN);
      
    } catch (err) {
      // 6. Handle error: show error message, toast
      const errorMessage = err instanceof Error ? err.message : "Failed to create admin user";
      setError(errorMessage);
      toastService.error(errorMessage);
    } finally {
      // 7. Clear loading state
      setLoading(false);
    }
  };

  // Check superadmin access on component mount and during operation
  useEffect(() => {
    if (!isInitializing && isAuthenticated && !isSuperAdmin()) {
      setError("Only superadmin can create new admin users");
    }
  }, [isSuperAdmin, isInitializing, isAuthenticated]);

  // Clear messages when form values change
  useEffect(() => {
    if (success || error) {
      const timer = setTimeout(() => {
        setSuccess("");
        setError("");
      }, 5000); // Auto-clear messages after 5 seconds
      
      return () => clearTimeout(timer);
    }
  }, [success, error]);

  // Show loading state during initialization
  if (isInitializing || !isClient) {
    return (
      <div className="max-w-lg p-4 mx-auto">
        <div className="flex items-center justify-center p-8">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin" />
          <span className="ml-3 text-slate-600 dark:text-slate-400">Loading...</span>
        </div>
      </div>
    );
  }

  if (!isSuperAdmin()) {
    return (
      <div className="max-w-lg p-4 mx-auto">
        <div className="p-6 text-center border border-red-200 rounded-lg bg-red-50 dark:bg-red-900/10 dark:border-red-500/20">
          <AlertTriangle className="w-12 h-12 mx-auto mb-4 text-red-500" />
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-200">Access Denied</h2>
          <p className="mt-2 text-slate-600 dark:text-slate-400">Only superadmin users can create new admin accounts.</p>
          <button 
            type="button"
            onClick={() => router.push('/admin-panel')} 
            className="px-4 py-2 mt-6 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700"
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-[600px] mx-auto">
      <div className="overflow-hidden border shadow-2xl bg-white/95 dark:bg-slate-800/95 backdrop-blur-md border-white/20 dark:border-slate-700/30 rounded-2xl shadow-slate-900/10 dark:shadow-black/20">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 dark:border-slate-700">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Create Admin User</h2>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Create new admin user accounts (Superadmin only)</p>
        </div>

        <form onSubmit={form.handleSubmit(onSubmit)} className="p-6 space-y-6">
          {/* Email */}
          <div>
            <label htmlFor="email" className="block mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">Email Address</label>
            <div className="relative">
              <Mail className="absolute w-5 h-5 -translate-y-1/2 left-3 top-1/2 text-slate-400" />
              <input id="email" type="email" {...form.register("email")} className={cn("w-full h-11 pl-10 pr-4 bg-white border rounded-md dark:bg-slate-900/50 border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500", form.formState.errors.email && "border-red-500")} />
            </div>
            {form.formState.errors.email && <p className="mt-1 text-xs text-red-600">{form.formState.errors.email.message}</p>}
          </div>

          {/* Password */}
          <div>
            <label htmlFor="password"  className="block mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">Password</label>
            <div className="relative">
              <Lock className="absolute w-5 h-5 -translate-y-1/2 left-3 top-1/2 text-slate-400" />
              <input id="password" type={showPassword ? "text" : "password"} {...form.register("password")} className={cn("w-full h-11 pl-10 pr-10 bg-white border rounded-md dark:bg-slate-900/50 border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500", form.formState.errors.password && "border-red-500")} />
              <button 
                type="button" 
                onClick={() => setShowPassword(!showPassword)} 
                className="absolute -translate-y-1/2 right-3 top-1/2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"
              >
                {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
              </button>
            </div>
            <PasswordStrengthIndicator password={passwordValue} />
            {form.formState.errors.password && <p className="mt-1 text-xs text-red-600">{form.formState.errors.password.message}</p>}
          </div>

          {/* Confirm Password */}
          <div>
            <label htmlFor="confirmPassword"  className="block mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">Confirm Password</label>
            <div className="relative">
              <Lock className="absolute w-5 h-5 -translate-y-1/2 left-3 top-1/2 text-slate-400" />
              <input id="confirmPassword" type={showConfirmPassword ? "text" : "password"} {...form.register("confirmPassword")} className={cn("w-full h-11 pl-10 pr-10 bg-white border rounded-md dark:bg-slate-900/50 border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500", form.formState.errors.confirmPassword && "border-red-500")} />
              <button 
                type="button" 
                onClick={() => setShowConfirmPassword(!showConfirmPassword)} 
                className="absolute -translate-y-1/2 right-3 top-1/2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"
              >
                {showConfirmPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
              </button>
            </div>
            {form.formState.errors.confirmPassword && <p className="mt-1 text-xs text-red-600">{form.formState.errors.confirmPassword.message}</p>}
          </div>

          {/* Role */}
          <div>
            <label htmlFor="role" className="block mb-1 text-sm font-medium text-slate-700 dark:text-slate-300">Admin Role</label>
            <select 
              id="role" 
              {...form.register("role")} 
              className={cn(
                "w-full px-3 bg-white border rounded-md h-11 dark:bg-slate-900/50 border-slate-300 dark:border-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500",
                form.formState.errors.role && "border-red-500"
              )}
            >
              <option value={UserRole.ADMIN}>{getRoleDisplayName(UserRole.ADMIN)}</option>
              <option value={UserRole.SUPERADMIN}>{getRoleDisplayName(UserRole.SUPERADMIN)}</option>
            </select>
            {form.formState.errors.role && <p className="mt-1 text-xs text-red-600">{form.formState.errors.role.message}</p>}
          </div>

          {/* Messages */}
          {success && (
            <div className="flex items-start gap-3 p-3 text-sm font-medium text-green-800 border border-green-200 rounded-lg dark:text-green-300 bg-green-50 dark:bg-green-900/10 dark:border-green-500/20 animate-slideInDown">
              <CheckCircle2 className="w-5 h-5 mt-0.5" />
              {success}
            </div>
          )}
          {error && (
            <div className="flex items-start gap-3 p-3 text-sm font-medium text-red-800 border border-red-200 rounded-lg dark:text-red-400 bg-red-50 dark:bg-red-900/10 dark:border-red-500/20 animate-shake">
              <AlertTriangle className="w-5 h-5 mt-0.5" />
              {error}
            </div>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-4 border-t border-slate-200 dark:border-slate-700">
            <button 
              type="button" 
              onClick={() => router.push('/admin-panel')} 
              className="px-4 py-2 text-sm font-medium transition-colors bg-white border rounded-lg text-slate-700 dark:text-slate-200 dark:bg-slate-700 border-slate-300 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-600"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Panel
            </button>
            <button 
              type="submit" 
              disabled={loading || form.formState.isSubmitting || !isSuperAdmin()}
              className="flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-white rounded-lg bg-[linear-gradient(45deg,_#667eea_0%,_#764ba2_100%)] hover:-translate-y-0.5 hover:shadow-[0_8px_25px_rgba(102,126,234,0.3)] transition-all duration-300 disabled:opacity-70 disabled:cursor-not-allowed disabled:transform-none disabled:shadow-none"
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <UserPlus className="w-4 h-4" />}
              {loading ? "Creating..." : "Create Admin User"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
